// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30_MJrd7x10kjSthZzGzfAHp443-4B6c',
    appId: '1:851750852031:web:b0443b809e2d5c4a40bd0a',
    messagingSenderId: '851750852031',
    projectId: 'ai-health-diary-app',
    authDomain: 'ai-health-diary-app.firebaseapp.com',
    storageBucket: 'ai-health-diary-app.firebasestorage.app',
    measurementId: 'G-3XCZ7Q9HL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCIyavf3Ihiu3lG7yLAV_A4KAcw6qY2c',
    appId: '1:851750852031:android:029e7896db0ae8af40bd0a',
    messagingSenderId: '851750852031',
    projectId: 'ai-health-diary-app',
    storageBucket: 'ai-health-diary-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4BQegWgyJyzKVFNAoI2j2uzfAPsP-bd4',
    appId: '1:851750852031:ios:daf401991ac7cf5440bd0a',
    messagingSenderId: '851750852031',
    projectId: 'ai-health-diary-app',
    storageBucket: 'ai-health-diary-app.firebasestorage.app',
    iosBundleId: 'com.example.stopwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4BQegWgyJyzKVFNAoI2j2uzfAPsP-bd4',
    appId: '1:851750852031:ios:daf401991ac7cf5440bd0a',
    messagingSenderId: '851750852031',
    projectId: 'ai-health-diary-app',
    storageBucket: 'ai-health-diary-app.firebasestorage.app',
    iosBundleId: 'com.example.stopwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA30_MJrd7x10kjSthZzGzfAHp443-4B6c',
    appId: '1:851750852031:web:166f278c6800780240bd0a',
    messagingSenderId: '851750852031',
    projectId: 'ai-health-diary-app',
    authDomain: 'ai-health-diary-app.firebaseapp.com',
    storageBucket: 'ai-health-diary-app.firebasestorage.app',
    measurementId: 'G-N9LGV4WDT6',
  );
}
